import {escapeHTML as h, duration, DAYS} from '../domain/alarm.js';
import {alarmSounds, ambientSounds} from '../audio/catalog.js';

export const missions = {
  math:{name:'Toán học',icon:'🧠',desc:'Giải đúng từng phép tính để bắt đầu ngày mới.',count:3},
  memory:{name:'Ghi nhớ',icon:'🧩',desc:'Ghi nhớ vị trí các ô sáng rồi chọn lại.',count:3},
  typing:{name:'Gõ chữ',icon:'⌨️',desc:'Gõ chính xác câu đã chọn, bao gồm dấu tiếng Việt.',count:1},
  shake:{name:'Lắc điện thoại',icon:'📱',desc:'Đếm chuyển động bằng cảm biến gia tốc khi thiết bị hỗ trợ.',count:30},
  walking:{name:'Đi bộ',icon:'👟',desc:'Bộ đếm thủ công trên bản web. Chưa tự nhận diện bước chân.',count:30},
  squats:{name:'Squats',icon:'🏋️',desc:'Tự xác nhận từng lần hoàn thành. Web chưa kiểm tra tư thế.',count:10},
  photo:{name:'Chụp ảnh',icon:'📷',desc:'Mở camera, chụp và tự đối chiếu ảnh mẫu. Chưa có AI nhận diện.',count:1},
  qr:{name:'Quét QR / mã vạch',icon:'▦',desc:'Đọc mã bằng camera trên trình duyệt hỗ trợ BarcodeDetector.',count:1},
};
export const missionRoute = id => `C${({math:2,memory:3,shake:4,photo:5,qr:6,typing:7,walking:8,squats:9})[id]}_${id}_setup`;
export const defaultSentence = 'Mỗi sáng thức dậy là một cơ hội mới để trở thành phiên bản tốt hơn của chính mình.';
const btn = (text, action, value = '', cls = 'btn-secondary') => `<button class="${cls}" data-do="${action}" data-value="${h(value)}">${text}</button>`;
const route = (text, screen, cls) => btn(text,'navigate',screen,cls);
const note = text => `<p class="z-note">${text}</p>`;
const card = html => `<section class="card z-card">${html}</section>`;
const field = (label,html) => `<label class="z-field"><span>${label}</span>${html}</label>`;
const input = (name,value,type='text',attrs='') => `<input class="z-input" data-field="${name}" id="field-${name}" type="${type}" value="${h(value)}" ${attrs}>`;
const toggle = (name,label,value,desc='') => `<label class="z-toggle"><span><strong>${label}</strong>${desc?`<small>${desc}</small>`:''}</span><input type="checkbox" data-field="${name}" ${value?'checked':''}></label>`;
const page = (title,body,back='B1_home',action='') => `<div class="screen-viewport"><header class="screen-header z-header">${back?route('‹',back,'btn-icon'):''}<h2>${title}</h2>${action||'<span></span>'}</header><div class="screen-content z-content">${body}</div></div>`;
const chips = (items,selected,action) => `<div class="z-chips">${items.map(v=>btn(h(v),action,v,`nap-chip ${selected===v?'z-selected':''}`)).join('')}</div>`;
const empty = (icon,title,text) => `<div class="z-empty"><span>${icon}</span><h3>${title}</h3><p>${text}</p></div>`;
const fmtDate = ts => new Date(ts).toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'});
const fmtTime = ts => new Date(ts).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});

export function renderFunctional(s) {
  const screen=s.currentScreen, d=s.editingAlarm, r=s.relaxation;
  if(screen==='A4_setup')return page('Thói quen của bạn',`<div class="z-hero"><span>🌅</span><h2>Bắt đầu từ một lịch ngủ</h2><p>Chọn giờ bạn muốn đi ngủ và thức dậy.</p></div>`+card(field('Giờ đi ngủ',input('bedtime',s.sleepSchedule.bedtime,'time'))+field('Giờ thức dậy',input('wakeTime',s.sleepSchedule.wakeTime,'time')))+note('Bạn có thể thay đổi các mốc giờ này bất cứ lúc nào. Sau bước cấp quyền, tạo báo thức để hẹn chuông.')+route('Tiếp tục · kiểm tra quyền','A5_permissions','btn-primary'),'A3_slides');
  if (screen==='B2_create_edit' && d) return page(s.alarms.some(a=>a.id===d.id)?'Sửa báo thức':'Tạo báo thức',
    `<div class="z-time-editor">${field('Giờ báo thức • 24 giờ',input('time',d.time,'time','required'))}</div>`+
    card(field('Tên báo thức',input('label',d.label,'text','maxlength="80" placeholder="Ví dụ: Thức dậy đi làm"')))+
    `<div class="z-settings-list">${[
      ['Lặp lại',d.days.length?d.days.join(', '):'Chỉ một lần','B3_repeat'],
      ['Nhiệm vụ',d.missions.length?d.missions.map(m=>missions[m]?.name).join(' → '):'Chạm để tắt chuông','C1_mission_library'],
      ['Âm thanh',`${h(d.sound)} · ${Math.round(d.volume*100)}%`,'B4_sound_picker'],
      ['Báo lại',d.snoozeEnabled?`${d.snoozeDuration} phút · tối đa ${d.snoozeMax} lần`:'Đã tắt','B5_snooze_config'],
      ['Tùy chọn nâng cao','Kiểm tra thức giấc, tăng âm lượng, đọc nhãn','B8_advanced'],
    ].map(([title,summary,to])=>`<button class="card z-row" data-do="navigate" data-value="${to}"><span><strong>${title}</strong><small>${summary}</small></span><span>›</span></button>`).join('')}</div>`+
    note('Giữ trang mở và thiết bị hoạt động để báo thức web có thể reo. Khi đóng trình duyệt hoặc máy ngủ, chuông không được bảo đảm.'),'B1_home',btn('Lưu','save-alarm','','btn-ghost text-mint'));
  if (screen==='B3_repeat' && d) return page('Lịch lặp lại',
    chips(['Ngày thường','Cuối tuần','Mỗi ngày','Một lần'],'','repeat-preset')+
    card([...DAYS.slice(1),DAYS[0]].map(day=>`<label class="z-toggle"><span>${day==='CN'?'Chủ nhật':`Thứ ${day.slice(1)}`}</span><input type="checkbox" data-day="${day}" ${d.days.includes(day)?'checked':''}></label>`).join(''))+
    note('Báo thức không lặp sẽ tự tắt sau lần reo tiếp theo.'),'B2_create_edit',route('Xong','B2_create_edit','btn-ghost text-mint'));
  if (screen==='B4_sound_picker' && d) {
    const catalog=[...alarmSounds,...s.customSounds];
    const filter=s.soundCategory||'Tất cả', search=(s.soundSearch||'').toLocaleLowerCase('vi');
    const found=catalog.filter(t=>(filter==='Tất cả'||t.category===filter)&&t.name.toLocaleLowerCase('vi').includes(search));
    return page('Nhạc báo thức',
      field('Tìm nhạc',input('soundSearch',s.soundSearch||'','search','placeholder="Tên bài, giai điệu…"'))+
      chips(['Tất cả',...new Set(catalog.map(t=>t.category))],filter,'sound-category')+
      card(field(`Âm lượng <span id="volume-label">${Math.round(d.volume*100)}%</span>`,input('volume',d.volume,'range','min="0.05" max="1" step="0.05"'))+toggle('vibrate','Rung khi báo thức',d.vibrate,'Tùy khả năng hỗ trợ của thiết bị.'))+
      `<div class="z-track-list">${found.map(t=>`<article class="card z-track ${d.soundId===t.id?'z-selected':''}"><button class="z-track-select" data-do="select-sound" data-value="${h(t.id)}" aria-pressed="${d.soundId===t.id}"><span class="z-cover">${t.icon||'🎵'}</span><span><strong>${h(t.name)}</strong><small>${h(t.category)} · ${h(t.author||'Trên thiết bị')}</small><span class="badge badge-mint">${h(t.license||'Nhạc của bạn')}</span></span></button>${btn(s.previewSound===t.id?'■':'▶','preview-sound',t.id,'btn-icon')}${t.id.startsWith('local_')?btn('×','delete-sound',t.id,'btn-icon'):''}</article>`).join('')||empty('🔎','Chưa có bài phù hợp','Thử từ khóa hoặc thể loại khác.')}</div>`+
      `<label class="btn-secondary z-upload">＋ Nhập nhạc từ thiết bị<input type="file" id="import-audio" accept="audio/*,.mp3,.wav,.ogg,.m4a" hidden></label>`+
      note('Nhập đoạn nhạc yêu thích/hottrend bạn có quyền dùng (tối đa 20 MB/file). Nhạc lưu trên trình duyệt này; không tải lên máy chủ. Các bản tích hợp EDM/retro là nhạc CC0, không phải bảng xếp hạng hottrend.')+
      `<details class="card z-card"><summary>Nguồn & giấy phép nhạc</summary>${alarmSounds.filter(t=>t.source).map(t=>`<p><a href="${t.source}" target="_blank" rel="noopener noreferrer">${h(t.name)} — ${h(t.author)}</a> · CC0</p>`).join('')}</details>`,
      'B2_create_edit',route('Xong','B2_create_edit','btn-ghost text-mint'));
  }
  if (screen==='B5_snooze_config' && d) return page('Hoãn báo thức',card(toggle('snoozeEnabled','Cho phép báo lại',d.snoozeEnabled))+card(field('Thời gian hoãn (phút)',input('snoozeDuration',d.snoozeDuration,'number','min="1" max="60"'))+field('Số lần tối đa',input('snoozeMax',d.snoozeMax,'number','min="1" max="10"')))+note('Khi hết số lần hoãn, cần hoàn thành nhiệm vụ hoặc dùng lối thoát khẩn cấp.'),'B2_create_edit',route('Xong','B2_create_edit','btn-ghost text-mint'));
  if (screen==='B8_advanced' && d) return page('Tùy chọn nâng cao',card(toggle('wakeupCheck','Kiểm tra thức giấc',d.wakeupCheck,'Sau khi hoàn thành nhiệm vụ, xác nhận trong 5 phút. Bỏ lỡ sẽ reo lại.')+toggle('boostSound','Tăng âm lượng dần',d.boostSound,'Tăng từ 10% đến âm lượng đã chọn trong 30 giây.')+toggle('speak','Đọc tên báo thức',d.speak,'Dùng giọng tiếng Việt nếu trình duyệt có sẵn.'))+note('Bản web không thể khóa thao tác đóng ứng dụng hoặc thay đổi âm lượng hệ thống.'),'B2_create_edit',route('Xong','B2_create_edit','btn-ghost text-mint'));
  if (screen==='B6_quick_alarm') return page('Một giấc nghỉ ngắn',`<div class="z-hero"><span>☁️</span><h2>Nạp lại năng lượng</h2><p>Chọn thời lượng để bắt đầu đếm ngược ngay.</p></div>`+chips([15,20,30,60],s.quickNap?.minutes||null,'start-nap')+card(field('Số phút tùy chọn',input('napMinutes',s.napMinutes||20,'number','min="1" max="180"')))+btn('Bắt đầu hẹn giờ','start-nap','','btn-primary')+note('Mỗi lần chỉ có một bộ đếm. Chọn thời lượng mới sẽ thay thời lượng cũ. Giữ trang mở để chuông reo.'));
  if (screen==='B9_nap_countdown') {
    const nap=s.quickNap;
    if (!nap) return page('Giấc nghỉ ngắn',empty('☁️','Chưa có hẹn giờ','Chọn thời lượng để bắt đầu chợp mắt.')+route('Chọn thời lượng','B6_quick_alarm','btn-primary'));
    return page('Đang chợp mắt',`<div class="z-hero"><span>☁️</span><h2>${nap.minutes} phút nghỉ ngơi</h2><div class="z-counter" id="quick-nap-countdown">${duration(Math.ceil((nap.deadline-Date.now())/1000))}</div><p>Chuông sẽ reo khi hết giờ.</p></div>`+note('Chọn mức khác để thay bộ đếm hiện tại; danh sách báo thức không thay đổi.')+chips([15,20,30,60],nap.minutes,'start-nap')+btn('Hủy hẹn giờ','cancel-nap','','btn-secondary')+route('Về trang báo thức','B1_home','btn-ghost'),'B1_home').replace('class="screen-viewport"','class="screen-viewport z-nap-screen"');
  }
  if (screen==='C1_mission_library' && d) return page('Nhiệm vụ thức giấc',note('Chọn nhiều nhiệm vụ và sắp xếp thứ tự. Các nhiệm vụ cảm biến có ghi rõ khả năng của bản web.')+
    Object.entries(missions).map(([id,m])=>`<article class="card z-track"><span class="z-cover">${m.icon}</span><div class="z-grow"><strong>${m.name}</strong><p class="text-small">${m.desc}</p><div class="z-inline">${btn('Cài đặt','navigate',missionRoute(id),'btn-ghost')}${btn(d.missions.includes(id)?'✓ Đã chọn':'＋ Chọn','toggle-mission',id,'btn-ghost text-mint')}</div></div></article>`).join('')+route(`Sắp xếp chuỗi (${d.missions.length})`,'C10_mission_sequence','btn-secondary'),'B2_create_edit',route('Xong','B2_create_edit','btn-ghost text-mint'));
  if (/^C[2-9]_/.test(screen) && d) {
    const id=screen.split('_')[1],m=missions[id],config=d.missionSettings?.[id]||{};
    let controls=field(id==='memory'?'Số ô cần nhớ':'Số lần / số câu',input('mission-count',config.count||m.count,'number',`min="1" max="${id==='memory'?7:100}"`));
    if(id==='math')controls+=field('Độ khó',`<select class="z-input" data-field="mission-difficulty">${['easy','medium','hard'].map((v,i)=>`<option value="${v}" ${(config.difficulty||'medium')===v?'selected':''}>${['Dễ · cộng trong 20','Vừa · cộng trong 100','Khó · nhân trong 144'][i]}</option>`).join('')}</select>`);
    if(id==='typing')controls=field('Câu cần gõ',`<textarea class="z-input" data-field="mission-sentence" maxlength="240">${h(config.sentence||defaultSentence)}</textarea>`);
    if(id==='qr')controls=field('Nội dung QR / mã vạch cần quét',input('mission-code',config.code||'','text','maxlength="500" placeholder="Nhập chính xác nội dung mã"'))+note('Camera chỉ xác nhận thành công khi giá trị quét được khớp mã này. Trình duyệt không hỗ trợ sẽ cung cấp nhiệm vụ toán thay thế.');
    if(id==='photo')controls=`<label class="btn-secondary z-upload">Chọn ảnh mẫu<input type="file" id="photo-reference" accept="image/*" hidden></label>${config.reference?`<img class="z-reference" src="${config.reference}" alt="Ảnh mẫu nhiệm vụ">`:''}`+note('Bạn tự đối chiếu ảnh sau khi chụp. Chưa tự động xác minh cảnh vật.');
    return page(m.name,`<div class="z-hero"><span>${m.icon}</span><p>${m.desc}</p></div>`+card(controls)+btn('Thử nhiệm vụ','try-mission',id,'btn-secondary')+btn('Lưu & thêm vào báo thức','save-mission',id,'btn-primary'),'C1_mission_library');
  }
  if(screen==='C10_mission_sequence' && d)return page('Chuỗi nhiệm vụ',note('Hoàn thành theo thứ tự từ trên xuống. Dùng mũi tên để đổi vị trí.')+d.missions.map((id,i)=>card(`<div class="z-inline"><span class="z-cover">${missions[id].icon}</span><strong class="z-grow">${i+1}. ${missions[id].name}</strong>${btn('↑','move-mission',`${i}:-1`,'btn-icon')}${btn('↓','move-mission',`${i}:1`,'btn-icon')}${btn('×','toggle-mission',id,'btn-icon')}</div>`)).join('')+(d.missions.length?'':empty('☀️','Tắt chuông bằng một chạm','Chọn nhiệm vụ để thêm thử thách.'))+route('＋ Thêm nhiệm vụ','C1_mission_library','btn-secondary')+btn('Thử toàn bộ chuỗi','try-sequence','','btn-primary'),'C1_mission_library',route('Xong','B2_create_edit','btn-ghost text-mint'));
  if(screen.startsWith('exec_')) return execution(s);
  if(screen.startsWith('D')) return wake(s);
  if(screen.startsWith('E')) return sleep(s);
  if(screen.startsWith('F')) return relax(s);
  if(screen==='G1_profile')return page('Cá nhân',card(`<div class="z-inline"><span class="z-cover">☀️</span><div class="z-grow"><h2>Không gian của bạn</h2><p>Hồ sơ trên thiết bị · Không cần tài khoản</p></div></div><div class="z-grid-2"><div><span class="z-counter">${s.alarms.filter(a=>a.enabled).length}</span><p>Báo thức đang bật</p></div><div><span class="z-counter">${s.sleepHistory.length}</span><p>Phiên nghỉ đã lưu</p></div></div>`)+`<span class="badge badge-mint">Tất cả tính năng đều miễn phí</span>`+[
    ['🎨','Giao diện','Màu sáng/tối, cỡ chữ','G2_appearance'],['🔔','Sẵn sàng báo thức','Thử chuông và kiểm tra quyền','G3_alarm_readiness'],['🔒','Dữ liệu & riêng tư','Xuất và xóa dữ liệu trên máy','G4_privacy'],['💬','Hướng dẫn sử dụng','Tìm hiểu tính năng của bản web','G5_help'],['✨','Về ZakiAlarm','Phiên bản và nguồn âm thanh','G6_about']
  ].map(([icon,title,desc,to])=>`<button class="card z-row" data-do="navigate" data-value="${to}"><span class="z-cover">${icon}</span><span class="z-grow"><strong>${title}</strong><small>${desc}</small></span><span>›</span></button>`).join(''),null);
  if(screen==='G2_appearance')return page('Giao diện',card(`<h3>Chế độ màu</h3>${chips(['Tối','Sáng'],s.theme==='dark'?'Tối':'Sáng','theme')}`)+card(`<h3>Kích thước chữ</h3>${chips(['Chuẩn','Lớn','Rất lớn'],({normal:'Chuẩn',large:'Lớn',xlarge:'Rất lớn'})[s.textScale],'text-scale')}<p class="z-font-preview">07:30 — Chào buổi sáng!<br>Một ngày mới đang chờ bạn.</p>`),'G1_profile');
  if(screen==='G3_alarm_readiness' || screen==='A5_permissions')return page('Sẵn sàng báo thức',
    card(`<h3>Âm thanh & trình duyệt</h3><p>Chạm “Thử chuông” để kích hoạt âm thanh. Giữ trang mở, máy hoạt động và kiểm tra âm lượng loa.</p>${btn('Thử chuông sau 5 giây','test-alarm','','btn-primary')}`)+
    Object.entries({notifications:'Thông báo',camera:'Camera',microphone:'Microphone',motion:'Chuyển động'}).map(([key,name])=>card(`<div class="z-row"><span><strong>${name}</strong><small>${({granted:'Đã cấp quyền',denied:'Đã từ chối',unsupported:'Thiết bị chưa hỗ trợ',default:'Chưa yêu cầu'})[s.permissions[key]]||'Chưa xác định'}</small></span>${btn('Kiểm tra','permission',key,'btn-secondary')}</div>`)).join('')+note('Quyền tùy chọn chỉ được yêu cầu khi bạn bấm. Muốn thu hồi quyền đã cấp, mở cài đặt trang web của trình duyệt.')+(screen==='A5_permissions'?route('Hoàn tất','B1_home','btn-primary'):''),screen==='A5_permissions'?'A4_setup':'G1_profile');
  if(screen==='G4_privacy')return page('Dữ liệu & riêng tư',card(`<h3>Dữ liệu trên thiết bị này</h3><p>${s.alarms.length} báo thức · ${s.sleepHistory.length} phiên nghỉ · ${s.customSounds.length} file nhạc</p><p>Không tài khoản, không đồng bộ đám mây. Xóa dữ liệu trình duyệt sẽ xóa thông tin đã lưu.</p>`)+btn('Xuất cài đặt & lịch sử (.json)','export','','btn-secondary')+note('Bản xuất không bao gồm file nhạc cục bộ. Hãy giữ bản gốc trên máy.')+(s.confirmDelete?card(`<h3>Xóa toàn bộ dữ liệu?</h3><p>Bao gồm báo thức, lịch sử, ảnh mẫu và nhạc đã nhập. Không thể hoàn tác.</p>${btn('Xóa vĩnh viễn','delete-confirm','','btn-danger')}${btn('Giữ dữ liệu','delete-cancel','','btn-secondary')}`):btn('Xóa toàn bộ dữ liệu','delete-request','','btn-danger')),'G1_profile');
  if(screen==='G5_help')return page('Hướng dẫn sử dụng',[
    ['Vì sao cần giữ trang mở?','Đây là ứng dụng web. Trình duyệt có thể dừng bộ đếm khi máy ngủ, tab bị đóng hoặc chạy nền. Muốn báo thức khi khóa máy cần ứng dụng native và cơ chế hẹn giờ hệ điều hành.'],
    ['Chọn nhạc riêng thế nào?','Mở báo thức → Âm thanh → Nhập nhạc từ thiết bị. Hỗ trợ định dạng trình duyệt đọc được, tối đa 20 MB/file. Nhạc được lưu tại trình duyệt này.'],
    ['Các nhiệm vụ hoạt động ra sao?','Toán, ghi nhớ và gõ chữ kiểm tra câu trả lời. Lắc dùng cảm biến nếu có. QR dùng BarcodeDetector. Đi bộ, squat và đối chiếu ảnh dùng xác nhận thủ công, được ghi rõ tại màn hình.'],
    ['Giấc ngủ được đo thế nào?','Nhật ký ghi thời gian từ lúc bắt đầu đến lúc kết thúc. Không suy ra REM, ngủ sâu, nhịp tim hoặc chẩn đoán ngáy từ bộ đếm.'],
    ['Quyền bị từ chối?','Mở cài đặt trang web trên trình duyệt để cấp lại quyền, sau đó quay lại mục Sẵn sàng báo thức.'],
  ].map(([q,a])=>`<details class="card z-card"><summary>${q}</summary><p>${a}</p></details>`).join(''),'G1_profile');
  if(screen==='G6_about')return page('Về ZakiAlarm',`<div class="z-hero"><img src="/logo.svg" alt="" width="80"><h1>ZakiAlarm</h1><p>Wake with purpose. Sleep with clarity.</p><span class="badge badge-mint">100% miễn phí · Không quảng cáo</span></div>`+card('<h3>Bản web 1.0</h3><p>Báo thức, nhiệm vụ thức giấc, nhật ký giấc ngủ và âm thanh thư giãn. Dữ liệu được lưu tại thiết bị.</p>')+`<div class="z-settings-list">${alarmSounds.filter(t=>t.source).map(t=>`<a class="card z-row" href="${t.source}" target="_blank" rel="noopener noreferrer"><span><strong>${h(t.name)}</strong><small>${h(t.author)} · CC0</small></span><span>↗</span></a>`).join('')}</div>`,'G1_profile');
  return null;
}

function execution(s){
  const id=s.currentScreen.slice(5),m=missions[id],run=s.missionRun;
  if(!run || run.id!==id)return page(m?.name||'Nhiệm vụ',note('Bắt đầu từ thư viện để áp dụng cấu hình và khởi tạo nhiệm vụ.')+btn('Bắt đầu thử','try-mission',id,'btn-primary'),'C1_mission_library');
  let body='';
  if(id==='math')body=`<div class="z-problem">${run.a} ${run.operator} ${run.b} = ?</div>${field(`Câu ${run.completed+1}/${run.count}`,input('answer',run.answer||'','text','inputmode="numeric" autocomplete="off" maxlength="5"'))}${btn('Kiểm tra đáp án','submit-math','','btn-primary')}`;
  if(id==='memory')body=`<p>${run.reveal?'Ghi nhớ các ô màu. Lưới sẽ ẩn sau 3 giây.':'Chọn lại đúng các ô vừa xuất hiện.'}</p><div class="z-memory">${Array.from({length:9},(_,i)=>`<button data-do="memory-cell" data-value="${i}" class="${(run.reveal?run.target:run.selected).includes(i)?'z-lit':''}" aria-label="Ô ${i+1}" aria-pressed="${run.selected.includes(i)}" ${run.reveal?'disabled':''}>${run.reveal&&run.target.includes(i)?'✦':''}</button>`).join('')}</div>${btn('Kiểm tra','submit-memory','','btn-primary')}`;
  if(id==='typing')body=card(`<blockquote id="target-sentence-text">${h(run.sentence)}</blockquote>`)+field('Gõ lại nguyên câu',`<textarea class="z-input" id="typing-answer" data-field="answer" rows="5" autocomplete="off">${h(run.answer||'')}</textarea>`)+btn('Kiểm tra câu đã gõ','submit-typing','','btn-primary');
  if(['shake','walking','squats'].includes(id))body=`<div class="z-counter">${run.completed}<small> / ${run.count}</small></div><progress max="${run.count}" value="${run.completed}"></progress>`+(id==='shake'?btn('Bật cảm biến chuyển động','start-motion','','btn-primary'):'')+note(id==='shake'?'Cảm biến chỉ đếm khi thiết bị phát sự kiện chuyển động. Nếu không có cảm biến, dùng nhiệm vụ toán thay thế.':'Chế độ đếm thủ công: mỗi lần bấm tương ứng một lần bạn tự xác nhận đã thực hiện.')+(id==='shake'?'':btn(id==='walking'?'＋ Đã đi một bước':'＋ Đã squat một lần','count-motion','','btn-primary'));
  if(id==='photo'||id==='qr')body=`<video id="mission-camera" autoplay playsinline muted class="z-camera"></video>${btn('Mở camera','start-camera',id,'btn-primary')}`+(id==='photo'?`${run.reference?`<img class="z-reference" src="${run.reference}" alt="Ảnh mẫu">`:''}${btn('Chụp ảnh','capture-photo','','btn-secondary')}${run.captured?`<img class="z-reference" src="${run.captured}" alt="Ảnh vừa chụp">${btn('Tôi xác nhận ảnh đúng vị trí','confirm-photo','','btn-primary')}`:''}${note('Đối chiếu thủ công, không có nhận diện AI tự động.')}`:note('Hướng camera vào mã đã đăng ký. Chỉ mã khớp mới hoàn thành nhiệm vụ.'));
  return page(m.name,`<span class="badge badge-lavender">${s.missionPractice?'Đang thử':'Đang thức giấc'} · Bước ${s.currentMissionStep+1}/${s.currentMissionSequence.length||1}</span>`+body+(!['math','memory','typing'].includes(id)?btn('Đổi sang nhiệm vụ toán','fallback-mission','','btn-secondary'):'')+btn(s.missionPractice?'Kết thúc thử':'Thoát khẩn cấp',s.missionPractice?'end-practice':'emergency','','btn-ghost'),null);
}

function wake(s){
  const a=s.ringingAlarm,screen=s.currentScreen;
  if(!a && screen!=='D6_morning_summary' && !(screen==='D3_mission_completed'&&s.missionPractice))return page('Thử báo thức',empty('🔔','Chưa có chuông đang reo','Bạn có thể thử chuông sau 5 giây để kiểm tra âm thanh.')+btn('Thử chuông','test-alarm','','btn-primary'));
  if(screen==='D1_ringing')return page('Đến giờ thức dậy',`<div class="z-hero"><span class="badge badge-mint">ĐANG ĐỔ CHUÔNG</span><div class="ringing-time-large">${h(a.time)}</div><h2>${h(a.label)}</h2><p>${h(a.sound)}</p><div class="pulsing-wake-ring"><img src="/logo.svg" alt="" width="70"></div></div>`+btn(a.missions.length?`Bắt đầu ${a.missions.length} nhiệm vụ`:'Tắt chuông','start-alarm-missions','','btn-primary')+(a.snoozeEnabled&&a.snoozeRemaining>0?btn(`Hoãn ${a.snoozeDuration} phút · còn ${a.snoozeRemaining} lần`,'snooze','','btn-secondary'):'')+btn('Thoát khẩn cấp','emergency','','btn-ghost'),null);
  if(screen==='D2_snoozing')return page('Ngủ thêm một chút',`<div class="z-hero"><span>☁️</span><h2>Chuông sẽ reo lại</h2><div class="z-counter" id="snooze-timer-digits">${duration((s.activeAlarmSession?.deadline-Date.now())/1000)}</div><p>Thời gian còn lại</p></div>`+btn('Dậy ngay · bắt đầu nhiệm vụ','start-alarm-missions','','btn-primary'),null);
  if(screen==='D3_mission_completed')return page('Hoàn thành!',`<div class="z-hero"><span>🎉</span><h2>Làm tốt lắm!</h2><p>Bạn đã hoàn thành bước ${s.currentMissionStep+1}.</p></div>`+btn(s.currentMissionStep+1<s.currentMissionSequence.length?'Nhiệm vụ tiếp theo':'Hoàn tất thức giấc','next-mission','','btn-primary'),null);
  if(screen==='D4_wakeup_check')return page('Bạn vẫn đang thức chứ?',`<div class="z-hero"><span>☀️</span><h2>Xác nhận tỉnh táo</h2><div class="z-counter" id="wakeup-timer">${duration((s.activeAlarmSession?.deadline-Date.now())/1000)}</div><p>Bỏ lỡ thời gian này, báo thức sẽ reo lại.</p></div>`+btn('Tôi đã tỉnh táo','confirm-awake','','btn-primary'),null);
  if(screen==='D5_emergency_exit')return page('Thoát khẩn cấp',note('Khi nhiệm vụ không phù hợp hoặc thiết bị gặp lỗi, chạm đủ 15 lần để tắt báo thức.')+`<div class="z-counter">${s.emergencyTapCount||0}<small> / 15</small></div>`+btn('Chạm để tắt','emergency-tap','','btn-danger')+btn('Quay lại báo thức','cancel-emergency','','btn-secondary'),null);
  return page('Chào buổi sáng',`<div class="z-hero"><span>🌅</span><h1>Ngày mới của bạn</h1><p>Đã hoàn tất báo thức lúc ${fmtTime(Date.now())}.</p></div>`+route('Về danh sách báo thức','B1_home','btn-primary')+route('Xem nhật ký giấc ngủ','E1_sleep_overview','btn-secondary'),null);
}

function sleep(s){
  const screen=s.currentScreen,history=s.sleepHistory||[],last=history.find(x=>x.id===s.selectedSleepId)||history.at(-1),active=s.sleepState;
  const report=last?card(`<span class="badge badge-lavender">${fmtDate(last.start)}</span><div class="z-counter">${Math.floor((last.end-last.start)/3600000)}<small> giờ </small>${Math.floor((last.end-last.start)/60000)%60}<small> phút</small></div><p>Thời gian phiên nghỉ đã ghi nhận</p><div class="z-inline"><span>🌙 ${fmtTime(last.start)}</span><span>☀️ ${fmtTime(last.end)}</span></div>`):empty('🌙','Chưa có phiên nghỉ','Bắt đầu một phiên để ghi lại giờ nghỉ và giờ thức dậy.');
  if(screen==='E1_sleep_overview')return page('Giấc ngủ',`<div class="z-hero z-sleep-hero"><span>🌙</span><h2>Một đêm an yên</h2><p>Chăm sóc thói quen nghỉ ngơi từng ngày.</p></div>`+route(active.isTracking?'Tiếp tục phiên đang ghi':'Bắt đầu phiên nghỉ',active.isTracking?'E4_active_session':'E3_sleep_prep','btn-primary')+report+`<div class="z-grid-2">${route('Lịch ngủ','E2_sleep_schedule','btn-secondary')}${route('Lịch sử','E6_history','btn-secondary')}${route('Xu hướng','E7_trends','btn-secondary')}${route('Bản ghi âm','E8_snore_recordings','btn-secondary')}</div>`+note('Nhật ký ghi thời gian nghỉ do bạn bắt đầu/kết thúc. Không đo giai đoạn ngủ, nhịp tim hoặc ngáy.'),null);
  if(screen==='E2_sleep_schedule')return page('Lịch ngủ của bạn',card(field('Giờ đi ngủ',input('bedtime',s.sleepSchedule.bedtime,'time'))+field('Giờ thức dậy',input('wakeTime',s.sleepSchedule.wakeTime,'time')))+note('Đây là mục tiêu lịch ngủ. Để chuông reo đúng giờ, tạo báo thức riêng trong tab Báo thức.')+btn('Lưu lịch ngủ','save-schedule','','btn-primary'),'E1_sleep_overview');
  if(screen==='E3_sleep_prep')return page('Chuẩn bị nghỉ ngơi',`<div class="z-hero"><span>✨</span><h2>Thả lỏng. Hít thở.</h2><p>Đặt thiết bị ở nơi thông thoáng, giảm ánh sáng và chuẩn bị một giấc nghỉ dễ chịu.</p></div>`+card(toggle('ambientInSleep','Phát tiếng mưa khi bắt đầu',active.ambientInSleep,'Tự tắt theo hẹn giờ thư giãn.'))+note('Thời gian phiên được lưu khi tải lại trang. Trình duyệt không tự xác định lúc bạn thật sự ngủ.')+btn('Bắt đầu ghi thời gian','start-sleep','','btn-primary'),'E1_sleep_overview');
  if(screen==='E4_active_session')return page('Đang nghỉ ngơi',`<div class="z-hero"><span>🌙</span><h2>Chúc bạn ngủ ngon</h2><div class="z-counter" id="sleep-elapsed">${duration(active.isTracking?(Date.now()-active.trackingStartTime)/1000:0)}</div><p>${active.isTracking?`Bắt đầu lúc ${fmtTime(active.trackingStartTime)}`:'Chưa bắt đầu phiên nghỉ'}</p></div>`+(active.isTracking?btn('Tôi đã dậy · kết thúc phiên','stop-sleep','','btn-primary'):route('Bắt đầu một phiên','E3_sleep_prep','btn-primary'))+route('Âm thanh thư giãn','F1_relax_library','btn-secondary'),'E1_sleep_overview');
  if(screen==='E5_night_report')return page('Báo cáo phiên nghỉ',report+note('Thời lượng này gồm cả thời gian nằm thức. Không có dữ liệu cảm biến để tính điểm ngủ, REM hoặc nhịp tim.')+(last?btn('Tải báo cáo (.json)','export-sleep',last.id,'btn-secondary'):''),'E1_sleep_overview');
  if(screen==='E6_history')return page('Lịch sử nghỉ ngơi',history.length?[...history].reverse().map(x=>`<button class="card z-row" data-do="view-sleep" data-value="${x.id}"><span><strong>${fmtDate(x.start)}</strong><small>${fmtTime(x.start)} → ${fmtTime(x.end)}</small></span><span>${Math.round((x.end-x.start)/60000)} phút ›</span></button>`).join(''):empty('📅','Lịch sử còn trống','Phiên nghỉ hoàn tất sẽ xuất hiện tại đây.'),'E1_sleep_overview');
  if(screen==='E7_trends') {
    const recent=history.filter(x=>x.end>=Date.now()-7*86400000),avg=recent.length?Math.round(recent.reduce((n,x)=>n+x.end-x.start,0)/recent.length/60000):0;
    return page('7 ngày gần đây',card(`<h3>Thời lượng trung bình mỗi phiên</h3><div class="z-counter">${Math.floor(avg/60)}<small>h </small>${avg%60}<small>p</small></div><p>${recent.length} phiên được ghi nhận</p>`)+(recent.length?`<div class="z-bars">${recent.slice(-7).map(x=>`<div><span>${Math.round((x.end-x.start)/60000)}p</span><i style="height:${Math.max(4,Math.min(160,(x.end-x.start)/3600000*16))}px"></i><small>${new Date(x.start).getDate()}/${new Date(x.start).getMonth()+1}</small></div>`).join('')}</div>`:empty('📊','Chưa đủ dữ liệu','Ghi lại một phiên nghỉ để bắt đầu theo dõi.')),'E1_sleep_overview');
  }
  return page('Âm thanh trong đêm',
    note('Ghi một mẫu âm thanh tối đa 60 giây bằng microphone. File lưu trên thiết bị; không tự phân loại tiếng ngáy và không ghi nền khi đóng trang.')+
    (s.recordingStarted ? card('<h3>● Đang ghi âm</h3><div class="z-counter" id="recording-timer">00:00</div>'+btn('Dừng & lưu','record-stop','','btn-primary')) : btn('🎙 Ghi mẫu 60 giây','record-start','','btn-primary'))+
    (s.recordings.length?[...s.recordings].reverse().map(clip=>card(`<div class="z-row"><span><strong>${fmtDate(clip.start)} · ${fmtTime(clip.start)}</strong><small>${Math.round((clip.end-clip.start)/1000)} giây · ${Math.round(clip.size/1024)} KB</small></span>${btn(s.playingRecording===clip.id?'■':'▶','record-play',clip.id,'btn-icon')}</div>${s.confirmRecordingDelete===clip.id?'<p>Xóa vĩnh viễn bản ghi này?</p>'+btn('Xóa','record-delete-confirm',clip.id,'btn-danger')+btn('Hủy','record-delete-cancel','','btn-secondary'):btn('Xóa bản ghi','record-delete',clip.id,'btn-ghost')}`)).join(''):empty('🎙️','Chưa có bản ghi âm','Bấm ghi mẫu để kiểm tra âm thanh phòng trước khi ngủ.')),'E1_sleep_overview');
}

function relax(s){
  const r=s.relaxation,screen=s.currentScreen,active=ambientSounds.find(x=>x.id===r.activeSound)||ambientSounds[0];
  if(screen==='F2_player')return page('Không gian thư giãn',`<div class="z-hero"><div class="relax-player-artwork ${r.isPlaying?'z-playing':''}"><span>${active.icon}</span></div><h2>${active.name}</h2><p>Âm thanh tổng hợp · Phát lặp</p></div>`+card(field('Âm lượng',input('relaxVolume',r.volume??0.6,'range','min="0" max="1" step="0.05"')))+`<div class="z-player-controls">${btn(r.favorites.includes(active.id)?'♥':'♡','favorite',active.id,'btn-icon')}${btn(r.isPlaying?'Ⅱ Tạm dừng':'▶ Phát','play-ambient',active.id,'btn-primary')}${route('⏱','F3_timer','btn-icon')}</div>`+`<p class="z-note" id="relax-countdown">${r.deadline?`Tự dừng sau ${duration((r.deadline-Date.now())/1000)}`:'Chưa hẹn giờ dừng'}</p>`,'F1_relax_library');
  if(screen==='F3_timer')return page('Hẹn giờ tắt âm thanh',chips([0,15,30,45,60,90],r.timerMinutes,'relax-timer')+card(toggle('fadeoutEnabled','Giảm âm lượng trước khi tắt',r.fadeoutEnabled,'Giảm dần trong 10 giây cuối.'))+note('Chọn 0 để phát liên tục. Hẹn giờ bắt đầu lại khi bấm áp dụng.')+btn('Áp dụng hẹn giờ','apply-timer','','btn-primary'),'F2_player');
  const sounds=ambientSounds.filter(x=>(screen!=='F4_favorites'||r.favorites.includes(x.id))&&(!s.relaxCategory||s.relaxCategory==='Tất cả'||x.category===s.relaxCategory)&&x.name.toLocaleLowerCase('vi').includes((s.relaxSearch||'').toLocaleLowerCase('vi')));
  return page(screen==='F4_favorites'?'Âm thanh yêu thích':'Thư giãn',field('Tìm âm thanh',input('relaxSearch',s.relaxSearch||'','search','placeholder="Mưa, sóng biển…"'))+chips(['Tất cả','Mưa & Nước','Thiên nhiên','Tiếng ồn'],s.relaxCategory||'Tất cả','relax-category')+sounds.map(x=>`<article class="card z-track"><button class="z-track-select" data-do="open-player" data-value="${x.id}"><span class="z-cover">${x.icon}</span><span><strong>${x.name}</strong><small>${x.category} · Âm tổng hợp</small></span></button>${btn(r.favorites.includes(x.id)?'♥':'♡','favorite',x.id,'btn-icon')}${btn(r.isPlaying&&r.activeSound===x.id?'Ⅱ':'▶','play-ambient',x.id,'btn-icon')}</article>`).join('')+(sounds.length?'':empty('♡','Chưa có âm thanh','Đổi bộ lọc hoặc bấm trái tim để lưu bài yêu thích.')),screen==='F4_favorites'?'F1_relax_library':null,route('♡','F4_favorites','btn-icon'));
}
